<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Quote') }} {{ $quote->displayNumber() }}</title>
    <style>
        @page { margin: 36px 42px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #0e1a1c; line-height: 1.5; }
        table { width: 100%; border-collapse: collapse; }
        .top td { vertical-align: top; }
        .company { font-size: 18px; font-weight: bold; }
        .title { font-size: 26px; font-weight: bold; color: {{ $accent }}; text-align: right; }
        .muted { color: #56676a; }
        .items { margin-top: 26px; }
        .items th { text-align: left; font-size: 9px; letter-spacing: 1px; text-transform: uppercase; color: #7d8f90; border-bottom: 1.5px solid #0e1a1c; padding: 6px 4px; }
        .items td { padding: 9px 4px; border-bottom: 1px solid #d9e2e2; }
        .right { text-align: right; }
        .totals { width: 45%; margin-left: 55%; margin-top: 14px; }
        .totals td { padding: 4px; }
        .grand td { font-size: 14px; font-weight: bold; border-top: 1.5px solid #0e1a1c; padding-top: 8px; }
        .footer { position: fixed; bottom: -10px; left: 0; right: 0; font-size: 9px; color: #7d8f90; text-align: center; }
    </style>
</head>
<body>
    <table class="top">
        <tr>
            <td>
                <div class="company">{{ $company['name'] }}</div>
                @if ($company['address'])<div class="muted" style="white-space: pre-line">{{ $company['address'] }}</div>@endif
                <div class="muted">{{ $company['email'] }}@if ($company['phone']) · {{ $company['phone'] }}@endif</div>
                @if ($company['tax_id'])<div class="muted">{{ setting('tax.id_label') }}: {{ $company['tax_id'] }}</div>@endif
            </td>
            <td class="right">
                <div class="title">{{ __('QUOTE') }}</div>
                <div><b>{{ $quote->displayNumber() }}</b></div>
            </td>
        </tr>
    </table>

    <table class="top" style="margin-top: 28px">
        <tr>
            <td style="width: 55%">
                <div class="muted" style="font-size: 9px; letter-spacing: 1px; text-transform: uppercase">{{ __('Prepared for') }}</div>
                <div><b>{{ $quote->client->company_name ?: $quote->client->name }}</b></div>
                @if ($quote->client->company_name)<div>{{ $quote->client->name }}</div>@endif
                <div>{{ collect([$quote->client->address_1, $quote->client->address_2])->filter()->implode(', ') }}</div>
                <div>{{ collect([trim($quote->client->postcode.' '.$quote->client->city), $quote->client->state, \App\Support\Countries::name($quote->client->country)])->filter()->implode(', ') }}</div>
                <div class="muted">{{ $quote->client->email }}</div>
                @if ($quote->client->tax_id)<div class="muted">{{ setting('tax.id_label') }}: {{ $quote->client->tax_id }}</div>@endif
            </td>
            <td class="right">
                <table>
                    <tr><td class="muted right">{{ __('Date') }}</td><td class="right" style="width: 45%">{{ ($quote->sent_at ?? $quote->created_at)->translatedFormat('d M Y') }}</td></tr>
                    <tr><td class="muted right">{{ __('Valid until') }}</td><td class="right">{{ $quote->valid_until->translatedFormat('d M Y') }}</td></tr>
                </table>
            </td>
        </tr>
    </table>

    <p style="margin-top: 24px; font-size: 13px"><b>{{ $quote->subject }}</b></p>

    <table class="items">
        <thead><tr><th>{{ __('Description') }}</th><th class="right" style="width: 22%">{{ __('Amount') }}</th></tr></thead>
        <tbody>
            @foreach ($quote->items as $item)
                <tr><td>{{ $item->description }}</td><td class="right">{{ money($item->amount, $quote->currency) }}</td></tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr><td class="muted">{{ __('Subtotal') }}</td><td class="right">{{ money($quote->subtotal, $quote->currency) }}</td></tr>
        @if ($quote->tax > 0)
            <tr><td class="muted">{{ $quote->taxLabel() }}</td><td class="right">{{ money($quote->tax, $quote->currency) }}</td></tr>
        @endif
        <tr class="grand"><td>{{ __('Total') }}</td><td class="right">{{ money($quote->total, $quote->currency) }}</td></tr>
    </table>

    @if ($quote->notes)
        <p style="margin-top: 30px; white-space: pre-line">{{ $quote->notes }}</p>
    @endif

    @if ($showPoweredBy)
        <div class="footer">{{ __('Quote generated by :product', ['product' => \App\Support\Branding::PRODUCT_NAME]) }} · {{ parse_url(\App\Support\Branding::PRODUCT_URL, PHP_URL_HOST) }}</div>
    @endif
</body>
</html>
